apiVersion: v1
kind: Service
metadata:
  name: promocode-factory-api-service
  labels:
    app: factory-api
    version: "2023"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 80
  selector:
    app.kubernetes.io/name: promocode-factory-api

