apiVersion: v1
kind: Pod
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "2023"
spec:
  containers:
  - name: promocode-factory-api
    image: свюю
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: promocode-factory-api-settings-vol
        mountPath: /app/config
  volumes:
    - name: promocode-factory-api-settings-vol
      configMap:
        name: promocode-factory-api-settings