apiVersion: v1
kind: Pod
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "2023"
spec:
  containers:
  - name: promocode-factory-api
    image: docker.io/dzitskiy/promocode-factory-api
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    livenessProbe:
      exec:
        command: 
         - cat 
         - /app/web.config
      initialDelaySeconds: 5
      timeoutSeconds: 1 # Default is 1
      periodSeconds: 5 # Default is 10
      failureThreshold: 2 # Default is 3
    readinessProbe:
      exec:
        command: 
         - cat 
         - /app/web.config
      initialDelaySeconds: 15
      timeoutSeconds: 5 # Default is 1
      periodSeconds: 30 # Default is 10
      failureThreshold: 5 # Default is 3
