apiVersion: v1
kind: Pod
metadata:
  name: promocode-factory-api
  labels:
    app: factory-api
    version: "12.2020"
spec:
  containers:
  - name: promocode-factory-api
    image: docker.io/dzitskiy/promocode-factory-api
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
